language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_adcf5152711f_key -iv $encrypted_adcf5152711f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
after_success:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - ./node_modules/.bin/codecov
